const { Router } = require('express');
const { SuccessResponseObject } = require('../common/http');
const demo = require('./demo.route');

const r = Router();

r.use('/demo', demo);

r.post('/web-api/auth/session/v2/verifySession', (req, res) => {
  const { traceId } = req.query;
  const data = {
    traceId,
    dt: {
      oj: {
        jid: 0
      },
      pid: "YkJ0gK6mPF",
      pcd: "09001_14330161668455_BRLFIAT_USD",
      tk: "4D8E1AF3-35D7-4957-9D16-8A36804898F5",
      st: 1,
      geu: "game-api/fortune-tiger/",
      lau: "/game-api/lobby/",
      bau: "web-api/game-proxy/",
      cc: "USD",
      cs: "$",
      nkn: "09001_14330161668455_BRLFIAT_USD",
      gm: [
        {
          gid: 126,
          msdt: 1638432092000,
          medt: 1638432092000,
          st: 1,
          amsg: "",
          rtp: {
            df: {
              min: 96.81,
              max: 96.81
            }
          },
          mxe: 2500,
          mxehr: 8960913
        }
      ],
      uiogc: {
        bb: 0,
        grtp: 1,
        gec: 0,
        cbu: 0,
        cl: 0,
        bf: 0,
        mr: 0,
        phtr: 0,
        vc: 0,
        bfbsi: 1,
        bfbli: 1,
        il: 0,
        rp: 0,
        gc: 1,
        ign: 1,
        tsn: 0,
        we: 0,
        gsc: 0,
        bu: 0,
        pwr: 0,
        hd: 0,
        et: 0,
        np: 0,
        igv: 0,
        as: 0,
        asc: 0,
        std: 0,
        hnp: 0,
        ts: 0,
        smpo: 0,
        ivs: 1,
        ir: 0,
        hn: 1
      },
      ec: [],
      occ: {
        rurl: "",
        tcm: "",
        tsc: 0,
        ttp: 0,
        tlb: "",
        trb: ""
      },
      ioph: "a68c2c72c62d"
    },
  };
  res.json(data);
});

r.post('/web-api/auth/session/v2/verifyOperatorPlayerSession', (req, res) => {
  const { traceId } = req.query;
  const data = {
    "dt": {
        "oj": {
            "jid": 0
        },
        "pid": "YkJ0gK6mPF",
        "pcd": "09001_14330161668455_BRLFIAT_USD",
        "tk": "F28D6454-BAD0-43C9-9088-16831D5DC85E",
        "st": 1,
        "geu": "game-api/fortune-tiger/",
        "lau": "/game-api/lobby/",
        "bau": "web-api/game-proxy/",
        "cc": "USD",
        "cs": "$",
        "nkn": "09001_14330161668455_BRLFIAT_USD",
        "gm": [
            {
                "gid": 126,
                "msdt": 1638432092000,
                "medt": 1638432092000,
                "st": 1,
                "amsg": "",
                "rtp": {
                    "df": {
                        "min": 96.81,
                        "max": 96.81
                    }
                },
                "mxe": 2500,
                "mxehr": 8960913
            }
        ],
        "uiogc": {
            "bb": 0,
            "grtp": 1,
            "gec": 0,
            "cbu": 0,
            "cl": 0,
            "bf": 0,
            "mr": 0,
            "phtr": 0,
            "vc": 0,
            "bfbsi": 1,
            "bfbli": 1,
            "il": 0,
            "rp": 0,
            "gc": 1,
            "ign": 1,
            "tsn": 0,
            "we": 0,
            "gsc": 0,
            "bu": 0,
            "pwr": 0,
            "hd": 0,
            "et": 0,
            "np": 0,
            "igv": 0,
            "as": 0,
            "asc": 0,
            "std": 0,
            "hnp": 0,
            "ts": 0,
            "smpo": 0,
            "ivs": 1,
            "ir": 0,
            "hn": 1
        },
        "ec": [],
        "occ": {
            "rurl": "",
            "tcm": "",
            "tsc": 0,
            "ttp": 0,
            "tlb": "",
            "trb": ""
        },
        "ioph": "fd0eb71b6be1"
    },
    "err": null
}
  res.json(data);
});

r.post('/web-api/game-proxy/v2/GameName/Get', (req, res) => {
  const { traceId } = req.query;
  const data = {
    traceId,
    status: 'success',
    data: {
        "dt": {
            "1": "Honey Trap of Diao Chan",
            "2": "Gem Saviour",
            "3": "Fortune Gods",
            "6": "Medusa 2: The Quest of Perseus",
            "7": "Medusa 1: The Curse of Athena",
            "18": "Hood vs Wolf",
            "20": "Reel Love",
            "24": "Win Win Won",
            "25": "Plushie Frenzy",
            "26": "Tree of Fortune",
            "28": "Hotpot",
            "29": "Dragon Legend",
            "33": "Hip Hop Panda",
            "34": "Legend of Hou Yi",
            "35": "Mr. Hallow-Win",
            "36": "Prosperity Lion",
            "37": "Santa's Gift Rush",
            "38": "Gem Saviour Sword",
            "39": "Piggy Gold",
            "40": "Jungle Delight",
            "41": "Symbols Of Egypt",
            "42": "Ganesha Gold",
            "44": "Emperor's Favour",
            "48": "Double Fortune",
            "50": "Journey to the Wealth",
            "53": "The Great Icescape",
            "54": "Captain's Bounty",
            "57": "Dragon Hatch",
            "58": "Vampire's Charm",
            "59": "Ninja vs Samurai",
            "60": "Leprechaun Riches",
            "61": "Flirting Scholar",
            "62": "Gem Saviour Conquest",
            "63": "Dragon Tiger Luck",
            "64": "Muay Thai Champion",
            "65": "Mahjong Ways",
            "67": "Shaolin Soccer",
            "68": "Fortune Mouse",
            "69": "Bikini Paradise",
            "70": "Candy Burst",
            "71": "CaiShen Wins",
            "73": "Egypt's Book of Mystery",
            "74": "Mahjong Ways 2",
            "75": "Ganesha Fortune",
            "79": "Dreams of Macau",
            "80": "Circus Delight",
            "82": "Phoenix Rises",
            "83": "Wild Fireworks",
            "84": "Queen of Bounty",
            "85": "Genie's 3 Wishes",
            "87": "Treasures of Aztec",
            "88": "Jewels of Prosperity",
            "89": "Lucky Neko",
            "90": "Secrets of Cleopatra",
            "91": "Guardians of Ice & Fire",
            "92": "Thai River Wonders",
            "93": "Opera Dynasty",
            "94": "Bali Vacation",
            "95": "Majestic Treasures",
            "97": "Jack Frost's Winter",
            "98": "Fortune Ox",
            "100": "Candy Bonanza",
            "101": "Rise of Apollo",
            "102": "Mermaid Riches",
            "103": "Crypto Gold",
            "104": "Wild Bandito",
            "105": "Heist Stakes",
            "106": "Ways of the Qilin",
            "107": "Legendary Monkey King",
            "108": "Buffalo Win",
            "110": "Jurassic Kingdom",
            "112": "Oriental Prosperity",
            "113": "Raider Jane's Crypt of Fortune",
            "114": "Emoji Riches",
            "115": "Supermarket Spree",
            "117": "Cocktail Nights",
            "118": "Mask Carnival",
            "119": "Spirited Wonders",
            "120": "The Queen's Banquet",
            "121": "Destiny of Sun & Moon",
            "122": "Garuda Gems",
            "123": "Rooster Rumble",
            "124": "Battleground Royale",
            "125": "Butterfly Blossom",
            "126": "Fortune Tiger",
            "127": "Speed Winner",
            "128": "Legend of Perseus",
            "129": "Win Win Fish Prawn Crab",
            "130": "Lucky Piggy",
            "132": "Wild Coaster",
            "135": "Wild Bounty Showdown",
            "1312883": "Prosperity Fortune Tree",
            "1338274": "Totem Wonders",
            "1340277": "Asgardian Rising",
            "1368367": "Alchemy Gold",
            "1372643": "Diner Delights",
            "1381200": "Hawaiian Tiki",
            "1397455": "Fruity Candy",
            "1402846": "Midas Fortune",
            "1418544": "Bakery Bonanza",
            "1420892": "Rave Party Fever",
            "1432733": "Mystical Spirits",
            "1448762": "Songkran Splash",
            "1451122": "Dragon Hatch2",
            "1473388": "Cruise Royale",
            "1489936": "Ultimate Striker",
            "1492288": "Pinata Wins",
            "1508783": "Wild Ape #3258",
            "1513328": "Super Golf Drive",
            "1529867": "Ninja Raccoon Frenzy",
            "1543462": "Fortune Rabbit",
            "1555350": "Forge of Wealth",
            "1568554": "Wild Heist Cashout",
            "1572362": "Gladiator's Glory",
            "1580541": "Mafia Mayhem",
            "1594259": "Safari Wilds",
            "1601012": "Lucky Clover Lady",
            "1615454": "Werewolf's Hunt",
            "1623475": "Anubis Wrath",
            "1635221": "Zombie Outbreak",
            "1655268": "Tsar Treasures",
            "1671262": "Gemstones Gold",
            "1682240": "Cash Mania",
            "1695365": "Fortune Dragon",
            "1717688": "Mystic Potion",
            "1738001": "Chicky Run",
            "1778752": "Futebol Fever"
        },
        "err": null
    }
  };
  res.json(data);
});

r.post('/game-api/fortune-tiger/v2/GameInfo/Get', (req, res) => {
  const { traceId } = req.query;
  const data = {
    traceId,
    status: 'success',
    data: {
        "dt": {
            "1": "Honey Trap of Diao Chan",
            "2": "Gem Saviour",
            "3": "Fortune Gods",
            "6": "Medusa 2: The Quest of Perseus",
            "7": "Medusa 1: The Curse of Athena",
            "18": "Hood vs Wolf",
            "20": "Reel Love",
            "24": "Win Win Won",
            "25": "Plushie Frenzy",
            "26": "Tree of Fortune",
            "28": "Hotpot",
            "29": "Dragon Legend",
            "33": "Hip Hop Panda",
            "34": "Legend of Hou Yi",
            "35": "Mr. Hallow-Win",
            "36": "Prosperity Lion",
            "37": "Santa's Gift Rush",
            "38": "Gem Saviour Sword",
            "39": "Piggy Gold",
            "40": "Jungle Delight",
            "41": "Symbols Of Egypt",
            "42": "Ganesha Gold",
            "44": "Emperor's Favour",
            "48": "Double Fortune",
            "50": "Journey to the Wealth",
            "53": "The Great Icescape",
            "54": "Captain's Bounty",
            "57": "Dragon Hatch",
            "58": "Vampire's Charm",
            "59": "Ninja vs Samurai",
            "60": "Leprechaun Riches",
            "61": "Flirting Scholar",
            "62": "Gem Saviour Conquest",
            "63": "Dragon Tiger Luck",
            "64": "Muay Thai Champion",
            "65": "Mahjong Ways",
            "67": "Shaolin Soccer",
            "68": "Fortune Mouse",
            "69": "Bikini Paradise",
            "70": "Candy Burst",
            "71": "CaiShen Wins",
            "73": "Egypt's Book of Mystery",
            "74": "Mahjong Ways 2",
            "75": "Ganesha Fortune",
            "79": "Dreams of Macau",
            "80": "Circus Delight",
            "82": "Phoenix Rises",
            "83": "Wild Fireworks",
            "84": "Queen of Bounty",
            "85": "Genie's 3 Wishes",
            "87": "Treasures of Aztec",
            "88": "Jewels of Prosperity",
            "89": "Lucky Neko",
            "90": "Secrets of Cleopatra",
            "91": "Guardians of Ice & Fire",
            "92": "Thai River Wonders",
            "93": "Opera Dynasty",
            "94": "Bali Vacation",
            "95": "Majestic Treasures",
            "97": "Jack Frost's Winter",
            "98": "Fortune Ox",
            "100": "Candy Bonanza",
            "101": "Rise of Apollo",
            "102": "Mermaid Riches",
            "103": "Crypto Gold",
            "104": "Wild Bandito",
            "105": "Heist Stakes",
            "106": "Ways of the Qilin",
            "107": "Legendary Monkey King",
            "108": "Buffalo Win",
            "110": "Jurassic Kingdom",
            "112": "Oriental Prosperity",
            "113": "Raider Jane's Crypt of Fortune",
            "114": "Emoji Riches",
            "115": "Supermarket Spree",
            "117": "Cocktail Nights",
            "118": "Mask Carnival",
            "119": "Spirited Wonders",
            "120": "The Queen's Banquet",
            "121": "Destiny of Sun & Moon",
            "122": "Garuda Gems",
            "123": "Rooster Rumble",
            "124": "Battleground Royale",
            "125": "Butterfly Blossom",
            "126": "Fortune Tiger",
            "127": "Speed Winner",
            "128": "Legend of Perseus",
            "129": "Win Win Fish Prawn Crab",
            "130": "Lucky Piggy",
            "132": "Wild Coaster",
            "135": "Wild Bounty Showdown",
            "1312883": "Prosperity Fortune Tree",
            "1338274": "Totem Wonders",
            "1340277": "Asgardian Rising",
            "1368367": "Alchemy Gold",
            "1372643": "Diner Delights",
            "1381200": "Hawaiian Tiki",
            "1397455": "Fruity Candy",
            "1402846": "Midas Fortune",
            "1418544": "Bakery Bonanza",
            "1420892": "Rave Party Fever",
            "1432733": "Mystical Spirits",
            "1448762": "Songkran Splash",
            "1451122": "Dragon Hatch2",
            "1473388": "Cruise Royale",
            "1489936": "Ultimate Striker",
            "1492288": "Pinata Wins",
            "1508783": "Wild Ape #3258",
            "1513328": "Super Golf Drive",
            "1529867": "Ninja Raccoon Frenzy",
            "1543462": "Fortune Rabbit",
            "1555350": "Forge of Wealth",
            "1568554": "Wild Heist Cashout",
            "1572362": "Gladiator's Glory",
            "1580541": "Mafia Mayhem",
            "1594259": "Safari Wilds",
            "1601012": "Lucky Clover Lady",
            "1615454": "Werewolf's Hunt",
            "1623475": "Anubis Wrath",
            "1635221": "Zombie Outbreak",
            "1655268": "Tsar Treasures",
            "1671262": "Gemstones Gold",
            "1682240": "Cash Mania",
            "1695365": "Fortune Dragon",
            "1717688": "Mystic Potion",
            "1738001": "Chicky Run",
            "1778752": "Futebol Fever"
        },
        "err": null
    }
  };
  res.json(data);
});


r.get('/', (req, res) => res.json(new SuccessResponseObject('express vercel boiler plate')));

module.exports = r;

